config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show create new] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    #raise
    if @bookmark.save
      redirect_to list_path(@list), notice: 'List was created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'List was created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Submit bookmark", class: "btn btn-primary" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <div class="container-fluid">
        <%= link_to lists_path, class: "navbar-brand" do %>
          <%= image_tag  "camera-logo.png" %>
        <% end %>
      </div>
    </div>
    <hr style="color:white; width:100%">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container-fluid main-poster mb-5">
  <div>
    <h1>Movie List App</h1>
    <h4>Save. Watch. Enjoy.</h4>
    <%= link_to 'Add List', new_list_path, class:'add-list-button' %>
  </div>
  <span><%= image_tag "cinema.png" %></span>

</div>
<hr style='color:white'>
<h1>Movie Lists</h1>

<ul>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 col-md-6 col-xl-4">
        <%= link_to list_path(list), class: 'list-link' do %>
          <div class="list-card">
            <li>
              <%= image_tag "camera.jpg" %>
              <p class='mt-3'><%= list.name.upcase %></p>
            </li>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</ul>

app/views/lists/new.html.erb
<div class="row">
  <div class="new-list-form col-12 col-lg-6">
    <h1>New List</h1>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name ,label_html: { class: "form-text"}%>
      <div class='button-center mt-5'>
      <%= f.submit class: 'create-list-button'%>
      </div>
    <% end %>
  </div>
  <div class="new-list-image col-lg-6">
    <%= image_tag "projector.jpg" %>
  </div>
</div>

app/views/lists/show.html.erb
<div class='container'>
  <h1><%= @list.name %></h1>

  <%= link_to 'Add a Bookmark',  new_list_bookmark_path(@list)%>


  <ul>
    <% @list.bookmarks.each do |bookmark| %>
      <li>
      <div class='card'>
      </div>
        <h4>
          <% movie = Movie.find(bookmark.movie_id) %>
          <%= movie.title %>
        </h4>
        <%= bookmark.comment %>
        <%= link_to 'Delete Bookmark',  bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </li>

    <% end %>
  </ul>
</div>